// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Interop {

struct TypeName;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlType;
struct XmlnsDefinition;

}

WINRT_EXPORT namespace winrt::Windows::UI::Xaml::Markup {

struct IXamlMetadataProvider;

}

WINRT_EXPORT namespace winrt::Da_Art {

struct IMainPage;
struct MainPage;
struct XamlMetaDataProvider;

}

namespace winrt::impl {

template <> struct category<Da_Art::IMainPage>{ using type = interface_category; };
template <> struct category<Da_Art::MainPage>{ using type = class_category; };
template <> struct category<Da_Art::XamlMetaDataProvider>{ using type = class_category; };
template <> struct name<Da_Art::IMainPage>{ static constexpr auto & value{ L"Da_Art.IMainPage" }; };
template <> struct name<Da_Art::MainPage>{ static constexpr auto & value{ L"Da_Art.MainPage" }; };
template <> struct name<Da_Art::XamlMetaDataProvider>{ static constexpr auto & value{ L"Da_Art.XamlMetaDataProvider" }; };
template <> struct guid_storage<Da_Art::IMainPage>{ static constexpr guid value{ 0x655EEE72,0x12C4,0x5278,{ 0xA2,0x96,0x39,0xAC,0x53,0xAD,0xB5,0x41 } }; };
template <> struct default_interface<Da_Art::MainPage>{ using type = Da_Art::IMainPage; };
template <> struct default_interface<Da_Art::XamlMetaDataProvider>{ using type = Windows::UI::Xaml::Markup::IXamlMetadataProvider; };

template <> struct abi<Da_Art::IMainPage>{ struct type : IInspectable
{
    virtual int32_t WINRT_CALL get_MyProperty(int32_t* value) noexcept = 0;
    virtual int32_t WINRT_CALL put_MyProperty(int32_t value) noexcept = 0;
};};

template <typename D>
struct consume_Da_Art_IMainPage
{
    int32_t MyProperty() const;
    void MyProperty(int32_t value) const;
};
template <> struct consume<Da_Art::IMainPage> { template <typename D> using type = consume_Da_Art_IMainPage<D>; };

}
