import "Models.SubModels.Deviation.Video.idl";
import "Models.SubModels.Deviation.Flash.idl";
import "Models.SubModels.Deviation.MotionBook.idl";
import "Models.SubModels.Deviation.Thumb.idl";
import "NullableString.idl";
import "Models.BaseModel.idl";

namespace UwpDeviation.Models
{
  [bindable][default_interface] runtimeclass Deviation : BaseModel
  {
    Deviation();
    Windows.Foundation.Collections.IVector<UwpDeviation.Models.SubModels.Deviation.Video> Videos;
    UwpDeviation.Models.SubModels.Deviation.Flash Flash;
    UwpDeviation.Models.SubModels.Deviation.MotionBook MotionBook;
    apicc.NullableString Excerpt;
    apicc.NullableString CategoryPath;
    Windows.Foundation.Collections.IVector<UwpDeviation.Models.SubModels.Deviation.Thumb> Thumbs;
  }
} // namespace UwpDeviantart.Models
